### ISSUE TITLE
validate that our documentation has HTML metadata

### ISSUE THREAD

**Issue by edublancas** [ploomber/contributing#39]
we should fail the CI if any document in our docs is missing HTML metadata

context: https://github.com/ploomber/sklearn-evaluation/issues/253

we can implement it as part of the `pkgmt check` command, since that runs in our CI already: https://github.com/ploomber/pkgmt/blob/main/src/pkgmt/cli.py#L56

**Comment by edublancas** [comment]
note that in jupyter-book 0.14 the format has changed from:

```yaml
html_meta:
    description lang=en: Create line, bar and pie charts from SQL queries in a Jupyter notebook using JupySQL
    keywords: jupyter, sql, jupysql, plotting, matplotlib
    property=og:locale: en_US
```

to

```yaml
myst:
  html_meta:
    description lang=en: Create line, bar and pie charts from SQL queries in a Jupyter notebook using JupySQL
    keywords: jupyter, sql, jupysql, plotting, matplotlib
    property=og:locale: en_US
```
